server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    # 用 ^~ 优先匹配 /blog/ 并 rewrite
    location ^~ /blog/ {
        rewrite ^/blog/(.*)$ /$1 break;
        try_files $uri $uri/ $uri.html /404.html;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;
    gzip_min_length 1000;
}
